### ISSUE TITLE
[FEATURE] support for certificate signed by unknown authority

### ISSUE THREAD

**Issue by ManCon** [bitgrip/cattlectl#22]
Hello

I like the idea of cattlectl very much.
I was follow the example on this post: https://medium.com/bitgrip/boosting-up-your-rancher-and-build-infrastructure-as-code-with-cattlectl-66ef7ea920eb 

Rancher: v2.2.2

Result:
root@server-01:~# cattlectl apply
ERRO[0000] Failed to create management client            error="Get https://192.168.178.101/v3: x509: certificate signed by unknown authority" rancher.url="https://192.168.178.101"
FATA[0000] Error creating rancher client                 error="Failed to create management client, Get https://192.168.178.101/v3: x509: certificate signed by unknown authority"

I am not sure for the reason of this ERROR but I don't have a trusted certificate for my local Rancher Server with the local IP: 192.168.178.101

Comes this ERROR from the self signed ssl certificate?
If yes how I can use cattlectl in this case?

Thanks in advance

**Comment by wtschreiter** [comment]
Hallo,

This case is not yet supported. But I guess this feature is needed quite often.

For the implementation see [clientbase. ClientOpts. Insecure](https://github.com/rancher/norman/blob/master/clientbase/common.go#L60)

Add to [1.1.0](https://github.com/bitgrip/cattlectl/projects/2)

**Comment by ManCon** [comment]
Hello

Thanks a lott. 
Yes it would be very useful if you can implement it in the next version.

Have a nice day.

**Comment by wtschreiter** [comment]
@ManCon This feature is now available starting with [v1.1.0-rc1](https://github.com/bitgrip/cattlectl/releases/tag/v1.1.0-rc1)

Any feat back is welcome.
